# Generated by Django 5.0.6 on 2024-06-13 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_remove_user_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authentication.user')),
                ('cellphone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=('authentication.user',),
        ),
    ]
