# Generated by Django 5.0.6 on 2024-06-13 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicoapp', '0001_initial'),
        ('pacienteapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(max_length=200)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicoapp.medico')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacienteapp.paciente')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacienteapp.statusconsulta')),
            ],
        ),
    ]
