# Generated by Django 5.0.6 on 2024-06-14 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacienteapp', '0002_statusconsulta_consulta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterField(
            model_name='consulta',
            name='date_time',
            field=models.DateTimeField(),
        ),
    ]
