# Generated by Django 5.0.6 on 2024-06-16 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacienteapp', '0003_alter_paciente_options_alter_consulta_date_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente',
            options={},
        ),
    ]
