# Generated by Django 5.0.6 on 2024-06-13 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_remove_user_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authentication.user')),
                ('crm', models.CharField(max_length=20)),
                ('especialidades', models.ManyToManyField(to='medicoapp.especialidade')),
            ],
            options={
                'abstract': False,
            },
            bases=('authentication.user',),
        ),
    ]
