# Generated by Django 5.0.6 on 2024-06-14 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medico',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
