# Generated by Django 5.0.6 on 2024-06-16 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicoapp', '0002_alter_medico_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medico',
            options={},
        ),
    ]
